name: 01-ghcr-push

on:
  push:
    tags:
      - '1.**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: cs4740/nginx-versions
  # You can tag the container image based on run number or git tag
  # IMAGE_TAG: 1.${{ github.run_number }} # GITHUB_RUN_NUMBER }}
  IMAGE_TAG: ${{ github.ref_name }}
  SVC_NAME: nginxVersions
  DOCKER_BUILDKIT: 1

jobs:

  build-push-ghcr:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set version in web page
        run: |
          sed -i -e "s/ZZZ/$IMAGE_TAG/g" "index.html"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: nmagee
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}

      # Now update another repo so that ArgoCD can deploy the new version.
      - name: Remote Dispatch RC
        run: |
          curl -X POST https://api.github.com/repos/uvarc/uvarc-services/dispatches \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -H "Authorization: token ${{ secrets.GHCR_PAT }}" \
            --data '{"event_type": "${{ env.IMAGE_NAME }} update to ${{ env.IMAGE_TAG }}", "client_payload": { "service": "${{ env.SVC_NAME }}", "version": "${{ env.IMAGE_TAG }}" }}'

      - name: Remote Dispatch SDS
        run: |
          curl -X POST https://api.github.com/repos/uvads/uvasds-services/dispatches \
            -H 'Accept: application/vnd.github.everest-preview+json' \
            -H "Authorization: token ${{ secrets.GHCR_PAT }}" \
            --data '{"event_type": "${{ env.IMAGE_NAME }} update to ${{ env.IMAGE_TAG }}", "client_payload": { "service": "${{ env.SVC_NAME }}", "version": "${{ env.IMAGE_TAG }}" }}'

