name: Remote Dispatch Action Responder

on: [repository_dispatch]

jobs:
  ping-pong:
    runs-on: ubuntu-latest
    steps:
      - name: Event Information
        run: |
          echo "Event '${{ github.event.action }}' received. Increase ${{ github.event.client_payload.service }} service to version ${{ github.event.client_payload.version }}."
